language: node_js
node_js:
  - '0.8'
  - '0.10'
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - 'cd frontend'
  - 'npm install -g bower grunt-cli'
  - 'ls'
  - 'bower install'
script:
  - 'grunt test'